### ISSUE TITLE
targetSdkVersion is set as 31

### ISSUE THREAD

**Issue by prashanthramakrishnan** [segmentio/analytics-kotlin#102]
**Describe the bug**
We've our app running with the targetSDKVersion as 30 and we cannot  latest Segment SDK In our app with version `1.7.0` as there the SDK is built with targetSDKVersion as 31.

**To Reproduce**
1. Use a sample app targeting compileSdkVersion 30
2. Use the latest Segment SDK - `1.7.0`
3. You see the below error. 

![image](https://user-images.githubusercontent.com/4025586/182840267-1e26887f-3b6f-4d13-91fa-7fd4ae1702c5.png)

**Expected behavior**
App should compile and the SDK should work as expected

**Screenshots**
See above:

**Platform (please complete the following information):**
 - Library Version in use: 1.7.0
 - Platform being tested: Android
 - Integrations in use: None as of now

**Additional context**
NA

**Comment by wenxi-zeng** [comment]
please read your error message `the minCompileSdk(31) specified in a dependency is greater than this module's compileSdkVersion (android-30)`

our minCompileSdk is 16. see [here](https://github.com/segmentio/analytics-kotlin/blob/main/android/build.gradle#L16), which is lower than your compileSdkVersion.

also, according to your error, the dependency is clearly `androidx.lifecycle:lifecylce-process:2.4.0`. you need to lower the version of androidx lifecycle.
