### ISSUE TITLE
identify(Traits) not found

### ISSUE THREAD

**Issue by julioromano** [segmentio/analytics-kotlin#106]
**Describe the bug**
I can't find the `identify(Traits)` api in analytics-kotlin even though the docstring of all the identify APIs clearly state:

```
Traits and userId will be automatically cached and available on future sessions for the
     * same user. To update a trait on the server, call identify with the same user id.
     * You can also use {@link #identify(Traits)} for this purpose.
```

**Comment by wenxi-zeng** [comment]
this issue is closed by #110. please use the latest build `1.9.0` to use this api
