### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant

### ISSUE THREAD

**Issue by codejunk1e** [segmentio/analytics-kotlin#116]
**Describe the bug**
App crashes on lower devices with java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;

**To Reproduce**
1. install SDK in app lower than 26 
2. Run app with any tracking made
3. App crashes with java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;

**Expected behavior**
App shouldn't crash!

**Screenshots**

**Platform (please complete the following information):**
 - Library Version in use: 1.9.0
 - Platform being tested: Android
 - Integrations in use: None

**Comment by wenxi-zeng** [comment]
see [public doc](https://segment.com/docs/connections/sources/catalog/libraries/mobile/kotlin-android/#getting-started) step 5 to enable desugaring

**Comment by MarinaShaposhnikova** [comment]
Hello @wenxi-zeng.
It is not an option for us to enable desugaring.
May I know if you can support lower than 26 Android API?

**Comment by wenxi-zeng** [comment]
hey @MarinaShaposhnikova, I'll bring it up to our team. would you mind to provide some details on your use case why does desugaring is not an option? it'd be helpful for us to make a decision. thanks!

**Comment by didiergarcia** [comment]
@MarinaShaposhnikova @codejunk1e 

We've released a new version that removes the use of `java.util.time.Instant` and which removes the need to desugar the SDK.

See: https://github.com/segmentio/analytics-kotlin/releases/tag/1.10.4
