### ISSUE TITLE
track function doesn't have userId argument

### ISSUE THREAD

**Issue by noymaor** [segmentio/analytics-kotlin#127]
**Describe the bug**
There is no option to add the userId argument in the `track` function, unlike in javascript SDK. Currently the workaround is creating the `TrackEvent` and passing it to `process`.

**Expected behavior**
`track` function has `userId` or `message` argument.

**Screenshots**
In this repo:
![image](https://user-images.githubusercontent.com/110397462/210388793-bd0d2bca-3ec8-4210-a665-a6b6862b933d.png)

In the javascript SDK (expected behavior, `userId` is part of `message: Identity`):
![image](https://user-images.githubusercontent.com/110397462/210389004-0626c632-3599-410c-abe1-f3a7f1e6e03b.png)

**Platform (please complete the following information):**
 - Library Version in use: 1.9.2
 - Platform being tested: Mac
 - Integrations in use: Amplitude

**Comment by wenxi-zeng** [comment]
hey @noymaor, this is by designed. the mobile SDK is not stateless, it remembers the user info from the last call to `identify` and applies that info to the payload automatically.

if in your use case, the userId is different for every track call, you can write a simple plugin for it:
```
class UserIdPlugin: EventPlugin {
    override val type: Plugin.Type = Plugin.Type.Enrichment
    override lateinit var analytics: Analytics

    override fun track(payload: TrackEvent): BaseEvent? {
        val event = super.track(payload)

        if (event is TrackEvent) {
            event.properties.getString("userId")?.apply {
                event.userId = this
                event.properties = updateJsonObject(event.properties) {
                    it.remove("userId")
                }
            }
        }

        return payload
    }
}
```

add the plugin to analytics and then use it like this:

```
analytics.track("test", buildJsonObject {
    put("userId", "YOUR USER ID")
    // other properties
})
```
