### ISSUE TITLE
Client Shutdown is different from Java library

### ISSUE THREAD

**Issue by zhouxos** [segmentio/analytics-kotlin#128]
I built my application using Spring, and I created a Segment Client bean. When I am trying to terminate my application I found out that my application termination hangs because the Segment Client bean is not destroyed properly. After more digging, I found out that the Client is never shut down properly. 

Looks like the java library has implemented the shutdown here https://github.com/segmentio/analytics-java/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L99

My questions are:
1. could we add something similar in Kotlin Lib? What is the correct way to shutdown the client
2. is calling `flush()` equivalent to `shutdown()` in Java Lib? (i could also use the java lib, since they are all JVM)
3. could provide some insights or guidance? 

Thanks

**Comment by wenxi-zeng** [comment]
got a decision back. we will add an api for shutdown, you can expect it in the next release. thanks!

**Comment by zhouxos** [comment]
thanks @wenxi-zeng! Do you need additional logs? If so I will need to spend some time to get a thread dump.

**Comment by wenxi-zeng** [comment]
@zhouxos yes please! that'd be super helpful!

**Comment by didiergarcia** [comment]
@zhouxos we've added a `shutdown()` function to analytics-kotlin that will release resources and should allow you to shutdown the bean properly.

See: https://github.com/segmentio/analytics-kotlin/blob/main/core/src/main/java/com/segment/analytics/kotlin/core/Analytics.kt#L543

Release: https://github.com/segmentio/analytics-kotlin/releases/tag/1.10.1
