### ISSUE TITLE
Document differences against segmentio/analytics-android

### ISSUE THREAD

**Issue by lwasyl** [segmentio/analytics-kotlin#129]
I saw https://github.com/segmentio/analytics-kotlin/issues/101 and there are differences in functionality pointed out between the two libraries, but ultimately there's nowhere to learn what differences still apply.

API compatibility can be verified by trying to migrate from `-android` to `-kotlin` library, but it'd be good to know what differences overall (so, missing features in API _or_ functional differences) are there between the two libraries.

**Comment by wenxi-zeng** [comment]
hey @lwasyl, are you referring to feature differences? I don't think there is any missing features. the kotlin lib supports everything android supports (middlewares/plugins, integrations/destinations, etc), and even more powerful than before (plugin is a much more flexible version of middleware, flush policy let's you control when/how to flush your data to remote, etc). the only things that I can think of it's "missing" are followings:
1. less supported integrations/destinations, but the popular ones are already covered, and the rest are coming up
2. [proxy http calls](https://segment.com/docs/connections/sources/catalog/libraries/mobile/android/#proxying-http-calls), a more flexible alternative is coming up, in the meanwhile, user can write a plugin to achieve the same

**Comment by lwasyl** [comment]
So, if I'm able to migrate to `analytics-kotlin` (as in, all the APIs are there), then there should be no loss in functionality whatsoever in e.g. data being sent, automatic breadcrumbs picked up (like for activities) etc. 👍 Sounds good :)
