### ISSUE TITLE
kotlin.UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by dostalleos** [segmentio/analytics-kotlin#140]
Hello, after updating the SDK to version 1.10.2 we have started seeing crash reports from your SDK.

You can see the stack trace below.

```
kotlin.UninitializedPropertyAccessException: lateinit property userInfo has not been initialized
        at com.segment.analytics.kotlin.core.Analytics.getUserInfo$core(Analytics:57)
        at com.segment.analytics.kotlin.core.Analytics.anonymousId(Analytics:641)
        at com.segment.analytics.kotlin.core.Analytics.anonymousIdAsync(Analytics:652)
```

I found that you made some changes to how the anonymous id is loaded. I see that now it's provided via `UserInfo` that is loaded asynchronously in the init. That's what caused the crash, we are getting the id right after the Analytics class is initiated. You have several sync methods that are accessing `UserInfo` that could not be loaded. 

Could you please fix it?

**Comment by wenxi-zeng** [comment]
hey @dostalleos, thanks for reporting this issue. we'll get it fixed this week.

**Comment by didiergarcia** [comment]
Hi @dostalleos, this should be fixed in the latest release:

https://github.com/segmentio/analytics-kotlin/releases/tag/1.10.3
