### ISSUE TITLE
`recordScreenViews` is missing in configuration

### ISSUE THREAD

**Issue by mozarty** [segmentio/analytics-kotlin#16]
**Describe the bug**
`recordScreenViews` is missing in the configuration file therefore i can't enable it

**To Reproduce**
https://github.com/segmentio/analytics-kotlin/blob/main/core/src/main/java/com/segment/analytics/kotlin/core/Configuration.kt

**Expected behavior**
recordScreenViews is an option in configurations

**Comment by prayansh** [comment]
Hi @mozarty! we have removed this config option and in place are asking users to add the [`AndroidRecordScreenPlugin`](https://github.com/segmentio/analytics-kotlin/blob/7be234e8858951c671e61c5d3f00a9f2bc41bcd3/samples/kotlin-android-app/src/main/java/com/segment/analytics/next/plugins/AndroidRecordScreenPlugin.kt). I would copy that plugin and it to your source files and ensure that you add the plugin itself to the analytics instance to enable auto screen tracking

I will make sure to update the readme to correctly reflect this as well. Apologies for the confusion

**Comment by prayansh** [comment]
Updated the README
