### ISSUE TITLE
Allow for `userId` to be passed to `track` calls for server-side use

### ISSUE THREAD

**Issue by wickstopher** [segmentio/analytics-kotlin#173]
**Is your feature request related to a problem? Please describe.**
Currently, correlating a `track` event to an individual user on the server requires making an `identify` call prior to any `track` calls. We'd like to avoid making frequent server-side `identify` calls as they aren't particularly useful to us, but would still like to be able to correlate a `track` event with a specific `userId`. This appears to be possible in the Java library. From your documentation:

```java
analytics.enqueue(TrackMessage.builder("Item Purchased")
    .userId("f4ca124298")
    .properties(ImmutableMap.builder()
        .put("revenue", 39.95)
        .put("shipping", "2-day")
        .build()
    )
);
```

**Describe the solution you'd like**
Add an overload for the `com.segment.analytics.kotlin.core.Analytics::track` method that accepts a `userId`, e.g.

```kotlin
track(
    userId = "12345", 
    name = "Event Name", 
    properties = JsonObject(mapOf("attribute" to JsonPrimitive("value")))
)
```

**Describe alternatives you've considered**
The only feasible alternative at the moment appears to be switching to the Java library.

**Additional context**

**Comment by wenxi-zeng** [comment]
@wickstopher please refer to #112 for solution

**Comment by wickstopher** [comment]
Thanks for the solution; this seems like a reasonable stopgap for avoiding switching to the Java library, but it would be nice to see this functionality ported over from your other SDKs. Has there been any consideration of separating out a server-side SDK for Kotlin that does not contain all of the Android dependencies and concerns?

**Comment by wenxi-zeng** [comment]
@wickstopher glad to hear it solves your problem. the plugin architecture is designed to provide customizability. since this use case can be addressed by a plugin in a relatively simple way, we are not going to add a new API for it.  

when adding dependency of the SDK, make sure you use `core` instead of `android` to avoid importing unnecessary android dependencies
