### ISSUE TITLE
Question: Is it safe to create more than one Analytics object with different configuration? 

### ISSUE THREAD

**Issue by dmcgloin** [segmentio/analytics-kotlin#175]
Wanting to know if it's OK to create two instances of the main Analytics class in a single application. I understand this is not recommended, but is it supported. We have case where we need to send some events to a separate pipeline.

Thanks for listening.

**Comment by wenxi-zeng** [comment]
yep. that's totally ok. in fact, that's one of the main factors we take into account when architect this SDK over the old android one.

**Comment by dmcgloin** [comment]
This is great! Thank you for quick response - and supporting this!. FYI: Asked same question for Apple SDK here: https://github.com/segmentio/analytics-swift/issues/235
