### ISSUE TITLE
analytics.kotlin:android:1.13.1 + destinations:firebase:1.5.4 make R8 build fail due to missing classes

### ISSUE THREAD

**Issue by limanup** [segmentio/analytics-kotlin#181]
**Describe the bug**
R8 build fail due to missing classes with these dependencies:
```
implementation 'com.segment.analytics.kotlin:android:1.13.1'
implementation 'com.segment.analytics.kotlin.destinations:firebase:1.5.4'
```
The missing classes:
`com.segment.analytics.kotlin.core.platform.plugins.logger.LogFilterKind`
and `com.segment.analytics.kotlin.core.platform.plugins.logger.LogTargetKt`

**To Reproduce**
1. Include these dependencies for an Android project:
```
implementation 'com.segment.analytics.kotlin:android:1.13.1'
implementation 'com.segment.analytics.kotlin.destinations:firebase:1.5.4'
```
2. build with `minifyReleaseWithR8`
3. See error:
> ERROR: R8: Missing class com.segment.analytics.kotlin.core.platform.plugins.logger.LogFilterKind (referenced from: com.segment.analytics.kotlin.core.BaseEvent com.segment.analytics.kotlin.destinations.firebase.FirebaseDestination.identify(com.segment.analytics.kotlin.core.IdentifyEvent) and 3 other contexts)
> Task :app:minifyReleaseWithR8 FAILED
Missing class com.segment.analytics.kotlin.core.platform.plugins.logger.LogTargetKt (referenced from: com.segment.analytics.kotlin.core.BaseEvent com.segment.analytics.kotlin.destinations.firebase.FirebaseDestination.identify(com.segment.analytics.kotlin.core.IdentifyEvent) and 3 other contexts)
4. can successfully build if revert back to below versions:
```
implementation 'com.segment.analytics.kotlin:android:1.9.2'
implementation 'com.segment.analytics.kotlin.destinations:firebase:1.5.1'
```

**Expected behavior**
Expect project to build

**Platform (please complete the following information):**
 - Library Version in use: analytics.kotlin:android:1.13.1
 - Platform being tested: Android
 - Integrations in use: Firebase destination

**Comment by wenxi-zeng** [comment]
hey @limanup, thanks for reporting this issue. we will get it fix asap.

**Comment by MichaelGHSeg** [comment]
The latest 1.5.5 release should resolve the build error.  Thanks!
