### ISSUE TITLE
Race condition in `AndroidContextPlugin` breaking `segment.device.id` initialization

### ISSUE THREAD

**Issue by kslesinski-godaddy** [segmentio/analytics-kotlin#182]
**Describe the bug**

After migrating to `analytics-kotlin` we noticed that _a lot_ of events are send with an empty `context.device.id` property.
As per the official [documentation](https://segment.com/docs/connections/sources/catalog/libraries/mobile/android/#analytics-android-and-unique-identifiers), device id initialization is asynchronous, so we were expecting very few initial events (i.e. `Application Installed`) to be sent with empty device id. However, we can clearly see that for a lot of users, the device id is not set _at all_ and remains an empty string for the entire user session.

**To Reproduce**

Tested the issue using Samsung Galaxy S9+, Android Emulator and Nexus 5. We managed to reproduce this issue locally once, when using Nexus 5 (our slowest device). The issue is difficult to reproduce as it is caused by a race condition.

1. Initialize Segment SDK with `collectDeviceId == false` (this is important)
2. Start sending events
3. Observe than `segment.device.id` property is always set to `""` (if the race condition occurs)

**Expected behavior**
`segment.device.id` should initially be set to an empty string `""` (default value when the SDK is initializing), but it should instantly be set to `anonymousId`.

**Platform (please complete the following information):**

 - Library Version in use: 1.13.1
 - Platform being tested: Android
 - Integrations in use: Firebase, Amplitude, Braze, Appsflyer, custom plugins (this is probably unrelated)

**Additional context**

This is _most probably_ a **race condition** in [AndroidContextPlugin](https://github.com/segmentio/analytics-kotlin/blob/2dc01742cc0fd6f33a7a4214d1496faf38e0bb42/android/src/main/java/com/segment/analytics/kotlin/android/plugins/AndroidContextPlugin.kt#L176C36-L176C36):

```
internal fun getDeviceId(collectDeviceId: Boolean, fallbackDeviceId: String): String {
        if (!collectDeviceId) {
            return storage.read(Storage.Constants.AnonymousId) ?: "" // RACE CONDITION between loading `anonymousId` and setting it properly in `storage` / shared prefs
        }
[...]
    }
```

When `AndroidContextPlugin` runs its `setup` and tries to load `Storage.Constants.AnonymousId` before the shared preference file is initialized, `getDeviceId()` will return an empty string - and will _not_ fall back to `fallbackDeviceId`.
Because of the code in `loadDeviceId` method, that empty string will be considered a valid device id:
```
if (deviceId != fallbackDeviceId) { // deviceId == "", fallbackDeviceId == UUID.randomUUID()
    device = updateJsonObject(device) {
        it[DEVICE_ID_KEY] = deviceId
    }
}
```
When using DRM-based ID (`collectDeviceId == true`), the issue does not occur, because the code will always fall back to `fallbackDeviceId` when a timeout or an error occurs.

**Fix suggestions**

- add proper synchronization so that `getDeviceId()` is called only after shared preferences file is initialized with defaults (i.e. so that `anonymousId` can be read properly).
- use `fallbackDeviceId` properly when `collectDeviceId == false`

**Comment by didiergarcia** [comment]
hi @kslesinski-godaddy. Thanks for report. I'm looking into this.

**Comment by kslesinski-godaddy** [comment]
While we're waiting for the official fix, are there any suggestions on how/if we can tackle this client-side? I.e. delaying `AndroidContextPlugin` initialization until `storage` is initialized properly, or using a custom plugin to overwrite `segment.device.id` with random/properly re-initialized UUID?

**Comment by wenxi-zeng** [comment]
hey @kslesinski-godaddy, yes, you can overwrite it through plugin like this:
```kotlin
class DeviceIdPlugin : EventPlugin {
    override val type: Plugin.Type = Plugin.Type.Enrichment
    override lateinit var analytics: Analytics

    override fun execute(event: BaseEvent): BaseEvent? {
        event.context = updateJsonObject(event.context) { context ->
            context["device"]?.safeJsonObject?.let { device -> 
                context["device"] = updateJsonObject(device) {
                    it["id"] = analytics.anonymousId()
                }    
            }
        }
        
        return event
    }
}
```

we're working on this issue. please expect a new release this week.

**Comment by wenxi-zeng** [comment]
hey @kslesinski-godaddy, `1.13.2` is out with the fix. please have a try and let us know if you're still experiencing the issue.
