### ISSUE TITLE
Question: analyticsContext.putDeviceToken in new SDK?

### ISSUE THREAD

**Issue by amusejfo** [segmentio/analytics-kotlin#213]
Hi, I am in the process of migrating from the old segment android sdk to this new one, we are running `analytics.analyticsContext.putDeviceToken` in the old one for some reason (We do not know what it is supposted to be used for)
is there an alternative in the new SDK or is it not needed anymore?

**Comment by wenxi-zeng** [comment]
hey @amusejfo, device token is not required. but if you want to keep using it for consistency purpose, you can write your own plugin to inject the token value. please follow [this comment](https://github.com/segmentio/analytics-kotlin/issues/113#issuecomment-1262771980) as an example. you will need to do something like below to add device token:
```kotlin
            event.context = updateJsonObject(event.context) { context ->
                context["device"] = updateJsonObject(device) { device ->
                    device["token"] = "YOUR TOKEN"
                }
            }
```

**Comment by amusejfo** [comment]
@wenxi-zeng event.putInContextUnderKey("device", "token", firebaseToken)
would be the same right?

**Comment by wenxi-zeng** [comment]
@amusejfo yep, you're right. we actually have an equivalent method of `analytics.analyticsContext.putDeviceToken`. see [here](https://github.com/segmentio/analytics-kotlin/blob/main/core/src/main/java/com/segment/analytics/kotlin/core/platform/plugins/DeviceToken.kt#L25)
