### ISSUE TITLE
Missing release notes for release version 1.15.0

### ISSUE THREAD

**Issue by isles1217** [segmentio/analytics-kotlin#216]
We were notified of an update for version 1.15.0 last week but there still aren't any release notes published. Can you please provide these in the Github releases page so we can review the changes? 

Thanks!

**Comment by wenxi-zeng** [comment]
hi @isles1217 thanks for bringing that to our attention. didn't noticed the release CI failed on creating notes at all. I just create a note manually. will fix the CI.

**Comment by isles1217** [comment]
Thanks!
