### ISSUE TITLE
How do I set UserInfo anonymousId?

### ISSUE THREAD

**Issue by nwagu** [segmentio/analytics-kotlin#233]
**Describe the bug**
I would like to set the anonymousId for a user, preferably when calling `identify`, but there is no overload of that method that allows this. Is there any other way to do this I am missing?

I have considered setting this in the EnrichmentClosure, but this only changes the anonymousId for the identify event. Other events still contain the random anonymous id generated internally by this lib.

**To Reproduce**
n/a

**Expected behavior**
I should be able to set anonymousId for a user from the client.

**Screenshots**
n/a

**Platform (please complete the following information):**
 - Library Version in use: 1.16.3
 - Platform being tested: Android
 - Integrations in use: Amplitude

**Additional context**
n/a

**Comment by wenxi-zeng** [comment]
hi @nwagu , you can do this via a plugin. please refer to [this comment](https://github.com/segmentio/analytics-kotlin/issues/112#issuecomment-1261112623) for example. if you'd like the anonymousId to stay once `identify` is called, you'd be doing something similar to the following:
```
// Pseudo code below 
class AnonymousIdPlugin : EventPlugin {
    anonymousId: String

    identify(event) {
        // update anonymousId with the value from event
        anonymousId = event.properties.anonymousId
    }

    execute(event) {
        // let super run first, so identify is called before overwriting anonymousId
       super.execute(event)

        // overwrite anonymousId with local variable
       event.anonymousId = anonymousId
    }
}
```

**Comment by nwagu** [comment]
Thanks, I did not know I could do this. 

But then this solution only modifies events, it does not change the actual userInfo, so calling something like `analytics.anonymousId()` still returns the internally generated anonymousId. Is there any reason why we should not be able to set the userInfo anonymousId?

**Comment by nwagu** [comment]
@wenxi-zeng could you please review my PR and see if it can be merged? It would be more convenient for us to set the anonymousId directly instead of using a plugin

**Comment by wenxi-zeng** [comment]
hi @nwagu sorry for delayed response. I have brought this to our team. the `anonymousId` is also used by the backend for other things. we need more discussion and evaluation to make this API changes across the board. in the meanwhile, please use the plugin to overwrite anonymousId and retrieve it via an extension function through your plugin instance. something like:
```
fun Analytics.myAnonymousId(): String {
    return anonymousIdPlugin. anonymousId;
}
```

**Comment by nwagu** [comment]
Okay. Could I get more info (maybe link to a doc) about what the anonymous id is used for in the backend? This is just so that I am clear what overwriting it implies @wenxi-zeng

**Comment by wenxi-zeng** [comment]
@nwagu one of the known use case is de-duping on backend. changing the anonymousId might not have any impact since we do have customers doing it via plugins and we hear no complains so far. we just have to be very cautious on making this change, since it's a public API and we need to evaluate the potential risk.
