### ISSUE TITLE
Use of unsupported java.time API in APIs < 26

### ISSUE THREAD

**Issue by AbanobNageh** [segmentio/analytics-kotlin#49]
**Describe the bug**
The `java.time` API is currently used on APIs < 26 but is not supported on those APIs and the current minimum SDK version is 16.

This causes the following Crash on APIs < 26:
```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
        at com.segment.analytics.kotlin.core.BaseEvent.applyBaseEventData$core(Events.kt:83)
        at com.segment.analytics.kotlin.core.Analytics.process(Analytics.kt:344)
        at com.segment.analytics.kotlin.core.Analytics.screen(Analytics.kt:217)
        at com.segment.analytics.kotlin.core.Analytics.screen$default(Analytics.kt:214)
```

see: https://developer.android.com/studio/write/java8-support#supported_features

**To Reproduce**
1. Try to use any function of this project that uses `java.time` such as `Instant.now()` in the screen tracking method on an SDK < 26.
2. See error.

**Expected behavior**
This project should work normally as the current minimum SDK version is 16.

**Screenshots**
N/A

**Platform (please complete the following information):**
 - Library Version in use: 1.3.0
 - Platform being tested: Android
 - Integrations in use: N/A

**Additional context**
N/A

**Comment by wenxi-zeng** [comment]
@AbanobNageh can you confirm what version of gradle plugin and android studio you're using? the sdk supports desugaring on gradle plugin 4.0 or above, which provides a subset of `java.time` that can be used on API even older than 26.
see https://developer.android.com/studio/write/java8-support#library-desugaring

**Comment by AbanobNageh** [comment]
I am using Gradle plugin version 4.2.2, I have tried desugaring and it works fine, thank you, it would be helpful if you add this to the library docs as a note maybe.

**Comment by wenxi-zeng** [comment]
great to hear it worked! thanks for the suggestion, we'll add a note to the doc in case people come across the same issue. close this issue out.
