### ISSUE TITLE
Call to constructor crashes app with "Could not create directory at /tmp/analytics-kotlin"

### ISSUE THREAD

**Issue by Jeehut** [segmentio/analytics-kotlin#51]
**Describe the bug**
When I start my app with this included, the app crashes right on start with this error:

```
java.io.IOException: Could not create directory at /tmp/analytics-kotlin/ABC123/events
        at com.segment.analytics.kotlin.core.utilities.FileUtils.createDirectory(FileUtils.kt:13)
        at com.segment.analytics.kotlin.core.utilities.EventsFileManager.<init>(EventsFileManager.kt:41)
        at com.segment.analytics.kotlin.core.utilities.StorageImpl.<init>(StorageImpl.kt:29)
        at com.segment.analytics.kotlin.core.utilities.ConcreteStorageProvider.getStorage(StorageImpl.kt:104)
        at com.segment.analytics.kotlin.core.Analytics.<init>(Analytics.kt:48)
        ...
```

**To Reproduce**
1. Call `segment = Analytics(Configuration(writeKey = "...", appContext))` from `onViewCreated` in a Fragment lifecycle
2. Run app (in debug mode) on Pixel C tablet emulator (API 29)
3. See error

**Expected behavior**
I expect the app not to crash at the very least. Also, if this is a misconfiguration, I would expect that the read access to directories etc. is documented in the documentation so we can make sure to give proper access. I followed the guide.

**Platform (please complete the following information):**
 - Library Version in use: 1.3.0
 - Platform being tested: Android
 - Integrations in use: N/A

**Comment by wenxi-zeng** [comment]
@Jeehut from your comment, seems like you are using the JVM storage provider in Android. the usage is a bit different. if you use the constructor directly, it by defaults uses JVM storage provider.
but in Android, you need to do it this way:
```kotlin
   Analytics("YOUR_WRITE_KEY", applicationContext) {
       // Automatically track Lifecycle events
       trackApplicationLifecycleEvents = true
       flushAt = 3
       flushInterval = 10
   }
```
another way is to specify android storage provider in configuration by yourself
`segment = Analytics(Configuration(writeKey = "...", appContext, storageProvider = AndroidStorageProvider))`

please find detailed android documentation here: https://segment.com/docs/connections/sources/catalog/libraries/mobile/kotlin-android/

let me know if that works for you. we'll try to enhance the documentation/usage to be less ambiguous

**Comment by bsneed** [comment]
Please reopen if necessary.
