### ISSUE TITLE
1.4.0 build is failing.

### ISSUE THREAD

**Issue by lzayas-chwy** [segmentio/analytics-kotlin#63]
https://jitpack.io/com/github/segmentio/analytics-kotlin/v1.4.0/build.log

**Comment by wenxi-zeng** [comment]
hi @lzayas-chwy from 1.4.0, we are going to host it on maven central. please allow us sometime to update the documentation. for the meanwhile try the following for android
```
    implementation 'com.segment.analytics.kotlin:android:1.4.0'
```
or below for jvm
```
    implementation 'com.segment.analytics:core:1.4.0'
```
