### ISSUE TITLE
Documentation still mentions jitpack which does not hold latest versions

### ISSUE THREAD

**Issue by Jasperste** [segmentio/analytics-kotlin#85]
**Describe the bug**
It seems like this repo's publishing to Maven, but the docs in https://segment.com/docs/connections/sources/catalog/libraries/server/kotlin/ still mention Jitpack. Meaning latest version can't be found. The non-server docs are updated and [do mention](https://segment.com/docs/connections/sources/catalog/libraries/mobile/kotlin-android/) Maven.

**To Reproduce**
1. Go to link above or try import latest versions via Jitpack vs Maven.
2. With Maven the latest version can be found, with Jitpack it goes up to 1.30 at max.

**Expected behavior**
Docs being updated to how it currently works with Maven.

**Comment by vesurbag** [comment]
I have the same, all versions after 1.3.0 are building with an error at the jitpack. 
```
⚠️ ERROR: No build artifacts found
Expected artifacts in: $HOME/.m2/repository/com/segment/analytics/kotlin/kotlin-jvm-app/1.6.2-SNAPSHOT
```
https://jitpack.io/com/github/segmentio/analytics-kotlin/1.6.2/build.log

**Comment by wenxi-zeng** [comment]
> I have the same, all versions after 1.3.0 are building with an error at the jitpack.
> 
> ```
> ⚠️ ERROR: No build artifacts found
> Expected artifacts in: $HOME/.m2/repository/com/segment/analytics/kotlin/kotlin-jvm-app/1.6.2-SNAPSHOT
> ```
> 
> https://jitpack.io/com/github/segmentio/analytics-kotlin/1.6.2/build.log

@vesurbag post 1.3.0, the artifacts are distributed to maven central. please update your dependency to the following:
```
 repositories {
   mavenCentral()
 }
 dependencies {
     implementation 'com.segment.analytics.kotlin:core:<latest_version>'
 }
```
we're updating the doc to show the correct usage.

**Comment by wenxi-zeng** [comment]
the doc is updated and will be released in this week. close this issue out
