### ISSUE TITLE
Debugger `Pretty` view not correctly displaying Kotlin SDK events

### ISSUE THREAD

**Issue by langsmith** [segmentio/analytics-kotlin#95]
**Describe the bug**

The debugger in my organization's Segment account doesn't seem to be correctly displaying information when I use the Kotlin SDK.

**To Reproduce**
1. Set up the SDK very minimally in order to send straightforward `screen` and/or `track` events.
2. Use `buildJsonObject` to add certain key/value pairs via the `put()` method.
3. Trigger the events within the app
4. See the events come into the debugger
5. See that they're not displayed in the same way that they are when using the "legacy" Segment SDK (https://github.com/segmentio/analytics-android)

**Expected behavior**

Expecting the debugger's `Pretty` view to display the data like it does 👇🏽  when I use the https://github.com/segmentio/analytics-android SDK. 

<img width="263" alt="Screen Shot 2022-06-30 at 7 06 45 PM" src="https://user-images.githubusercontent.com/4394910/176809201-5e587382-2543-489a-83d7-ea16d4969b49.png">

**Screenshots**

Kotlin SDK usage

<img width="355" alt="Screen Shot 2022-06-30 at 6 34 54 PM" src="https://user-images.githubusercontent.com/4394910/176809402-07bed9a6-a1e0-4b7b-8c53-3f9de3d69c3c.png">

<img width="354" alt="Screen Shot 2022-06-30 at 7 08 59 PM" src="https://user-images.githubusercontent.com/4394910/176809438-edf7ad21-e8f2-4f17-98b8-b8fbce4cb0b1.png">

https://github.com/segmentio/analytics-android usage

<img width="263" alt="Screen Shot 2022-06-30 at 7 06 45 PM" src="https://user-images.githubusercontent.com/4394910/176809201-5e587382-2543-489a-83d7-ea16d4969b49.png">

**Platform (please complete the following information):**
 - Library Version in use: https://github.com/segmentio/analytics-kotlin 1.7.0
 - Platform being tested: Android
 - Integrations in use: None

**Additional context**

**Comment by wenxi-zeng** [comment]
if you switch to `Raw` instead of `Pretty`, you will see the full payload in pretty format. this is the same in both analytics-android and analytics-kotlin, since the sdk has no control over to the format displaying the web page.

**Comment by wenxi-zeng** [comment]
came back from your the another issue you created. seems like you know how to view the actual json payload through `Raw`. so I'm confused what you are asking in this one. the first image you uploaded seems to be a duplication of the last one. please correct the image if it's mistaken or provide more details regarding to what you are expecting the content of `Pretty`. feel free to reopen the issue.

**Comment by langsmith** [comment]
> the first image you uploaded seems to be a duplication of the last one

Yes, that was on purpose.

I guess I was thrown off by the `Pretty` view having raw `curl` info with `-d` and everything. I'm not sure why the `Pretty` view now shows `anonymousId`, `receivedAt`, and other specific info such as the `writeKey`. It's difficult to read what properties were attached to the event.

If I use the legacy non-Kotlin SDK and use `Pretty` view, the `putValue()` key/value pairs are cleanly shown. The pairs are the only info that's shown besides the event's name.

**Comment by langsmith** [comment]
> feel free to reopen the issue

I would if I could. Doesn't seem that this repo's setup allows me to re-open the issue.

**Comment by bsneed** [comment]
@martymiller @langsmith These are issues in the Segment debugger and not the libraries themselves.  We've opened a ticket with the appropriate team internally.  If we get info on an ETA for fix, we'll report back here.

**Comment by langsmith** [comment]
Ok, I'd opened the tickets here because I thought it might have been an SDK issue related to how it was sending events to Segment's servers. Thanks for the update.

**Comment by bsneed** [comment]
@langsmith no problem, thanks for reporting it!  We had no idea. :(   Now it can get fixed.
