### ISSUE TITLE
Historical import

### ISSUE THREAD

**Issue by BodySplash** [segmentio/analytics-kotlin#99]
**Is your feature request related to a problem? Please describe.**
In the case of historical data import, it should be possible to specify a timestamp manually. 

**Describe the solution you'd like**
Just like [the java version](https://segment.com/docs/connections/sources/catalog/libraries/server/java/#historical-import), just being able to specify a timestamp should do the trick I guess. 

**Describe alternatives you've considered**
For now, I'm sticking to java library, even if the backend is in kotlin. It's not really a problem, it's just that the kotlin API is definitely more enjoyable, thanks to kotlinx.serialization and/or json builder (and maybe coroutines are slightly more efficient under the hood, but I didn't have a look at the numbers).

**Comment by wenxi-zeng** [comment]
hey @BodySplash, that's an useful feature on server we haven't thought about. I will discuss with the team see if we want to make it a public api. but in the meanwhile, you should be able to implement this functionality with a plugin easily:

```
    class TimestampPlugin: EventPlugin {
        override val type: Plugin.Type = Plugin.Type.Enrichment
        override lateinit var analytics: Analytics

        override fun track(payload: TrackEvent): BaseEvent? {
            val event = super.track(payload)

            if (event is TrackEvent) {
                event.properties.getString("timestamp")?.apply {
                    event.timestamp = this
                    event.properties = updateJsonObject(event.properties) {
                        it.remove("timestamp")
                    }
                }
            }

            return payload
        }
    }
```

and then add this plugin to analytics, when you track, do it like tihs:
```
analytics.track("test", buildJsonObject {
    put("timestamp", "YOUR TIMESTAMP")
    // other properties
})
``` 

this is an example of track event, you can modify it for other events. 

and YESSSS you're right about the performance part! the new plugin architecture and coroutine boost the performance 3x while using half of the resources. you can check out this [blog post](https://segment.com/blog/sdk-performance-improvements/) for details.
